
/*═══════════════════════════════════════════════════════════════════════════════════════════╗
║ READONLY SAMPLE: CustomSample_ExtendedMainMenuLayer
╟────────────────────────────────────────────────────────────────────────────────────────────╢
║ Do NOT edit this file in your custom project.
║ When starting a new custom project, copy this file and modify your copy.
║ Update CustomStartupInstruction.cs so that it refers to your copy instead of this sample.
╚═══════════════════════════════════════════════════════════════════════════════════════════*/

using System;
using System.Security.Claims;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using VPBase.Shared.Server.Services.Menu;

namespace VPBase.Custom.Server.Configuration.MenuLayers
{
    public class CustomSample_ExtendedMainMenuLayer : MenuLayerBase
    {
        public override string LayerHandle => "CUSTOM_MAIN";
        public override double LayerOrder => 12;
        
        public override bool IsApplicableForMenuIdentifier(string menuIdentifier)
        {
            return menuIdentifier == "MAIN";
        }

        public override void Apply(SubMenu rootNode, IUrlHelper urlHelper)
        {
            // A menu link that is only displayed on mondays (using custom code defined in method "CustomAccessCheckShowOnMondays" below.
            rootNode.AddLink("Måndag!", "https://voidpointer.se").RequireCustomAccessCheck(CustomAccessCheckShowOnMondays);
        }

        public static bool CustomAccessCheckShowOnMondays(ClaimsPrincipal user, HttpContext httpContext, IServiceProvider serviceProvider)
        {
            if (DateTime.Today.DayOfWeek == DayOfWeek.Monday)
            {
                return true;
            }

            return false;
        }
    }
}