// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VPBase.Custom.Core.Data;

#nullable disable

namespace VPBase.Custom.Core.Migrations
{
    [DbContext(typeof(CustomDatabaseManager))]
    [Migration("20241002083226_AddIsActivePropertyOnSimpleMvc")]
    partial class AddIsActivePropertyOnSimpleMvc
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Custom")
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VPBase.Custom.Core.Data.Entities.VP_Template_Mvc", b =>
                {
                    b.Property<string>("VP_Template_MvcId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("VP_Template_MvcId");

                    b.Property<DateTime?>("AnonymizedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VP_Template_MvcId");

                    b.ToTable("VP_Template_Mvcs", "Custom.Sample");
                });

            modelBuilder.Entity("VPBase.Custom.Core.Data.Entities.VP_Template_SimpleMvc", b =>
                {
                    b.Property<string>("VP_Template_SimpleMvcId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("VP_Template_SimpleMvcId");

                    b.Property<DateTime?>("AnonymizedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VP_Template_SimpleMvcId");

                    b.ToTable("VP_Template_SimpleMvcs", "Custom.Sample");
                });
#pragma warning restore 612, 618
        }
    }
}
