/*═══════════════════════════════════════════════════════════════════════════════════════════╗
║ READONLY SAMPLE: SampleCustomMenuPluginViewComponent
╟────────────────────────────────────────────────────────────────────────────────────────────╢
║ This sample shows how to plug in a customised section in the main menu using a 
║ view component. 
║
║ Do NOT edit this file in your custom project - copy it and create your own variant.
║ 
║ You plug it in by editing your appsettings.json like this:
║ "MenuSettings": { "CustomComponent": "SampleCustomMenuPlugin" }
╚═══════════════════════════════════════════════════════════════════════════════════════════*/

using Microsoft.AspNetCore.Mvc;

namespace VPBase.Custom.Server.Areas.Custom.ViewComponents
{
    public class SampleCustomMenuPluginViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View("/Areas/Custom/Views/Shared/Components/SampleCustomMenuPlugin/Default.cshtml");
        }
    }
}