/*═══════════════════════════════════════════════════════════════════════════════════════════╗
║ READONLY SAMPLE: SampleUserClaimsViewComponent
╟────────────────────────────────────────────────────────────────────────────────────────────╢
║ Do NOT edit this file in your custom project.
║ When starting a new custom project, copy this file and give it a proper name with the suffix: "...ViewComponent".
║ 
║ See this class as a "controller" for the specific view component.
║ This means you also need a view for it. See where and how the sample view is added (/Shared/Components/SampleUserClaims/Default.cshtml)
║ 
║ How do I render the view component? Add the following line: @await Component.InvokeAsync("SampleUserClaims") (see SampleIndex.cshtml)
╚═══════════════════════════════════════════════════════════════════════════════════════════*/

using Microsoft.AspNetCore.Mvc;

namespace VPBase.Custom.Server.Areas.Custom.ViewComponents
{
    public class SampleUserClaimsViewComponent : ViewComponent
    {
        public SampleUserClaimsViewComponent()
        {
            
        }

        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}
