
/*═══════════════════════════════════════════════════════════════════════════════════════════╗
║ READONLY SAMPLE: CustomSampleJob
╟────────────────────────────────────────────────────────────────────────────────────────────╢
║ Do NOT edit this file in your custom project.
║ When starting a new custom project, copy this file and modify your copy if you wish.
║ Then refer to your copy from your JobScheduler.
╚═══════════════════════════════════════════════════════════════════════════════════════════*/

using System;
using Microsoft.Extensions.Logging;
using VPBase.Shared.Server.Configuration;
using VPBase.Shared.Server.Jobs;

namespace VPBase.Custom.Server.Jobs
{
    public class CustomSampleJob : IJob
    {
        private readonly AppSettings _appSettings;
        private readonly ILogger _logger;

        public CustomSampleJob(AppSettings appSettings, ILogger<CustomSampleJob> logger)
        {
            _appSettings = appSettings;
            _logger = logger;
        }
        public void Run()
        {
            try
            {
                // Remember to check that task is enabled even if it is done in the JobScheduler.
                // Since this is just a sample, we are borrowing MailSettings
                if (_appSettings.MailSettings.TaskEnabled)
                {
                    var message = $"Printing favicon path: {_appSettings.FaviconUrl}";

                    _logger.LogDebug(message);
                }
            }
            catch (Exception e)
            {
                _logger.LogError(e, e.Message);
            }
        }
    }
}
